const clothesArray = [
  {
    id: "1",
    category: "pants",
    brand: "Brand D",
    color: "blue",
    size: "XXL",
    season: "autumn",
    wearCount: 47,
    cost: 187.37,
    formality: "casual",
    img: "",
  },
  {
    id: "2",
    category: "sweater",
    brand: "Brand B",
    color: "white",
    size: "S",
    season: "summer",
    wearCount: 32,
    cost: 30.25,
    formality: "casual",
    img: "",
  },
  {
    id: "3",
    category: "pants",
    brand: "Brand C",
    color: "red",
    size: "XL",
    season: "spring",
    wearCount: 21,
    cost: 96.03,
    formality: "casual",
    img: "",
  },
  {
    id: "4",
    category: "shirt",
    brand: "Brand B",
    color: "blue",
    size: "L",
    season: "spring",
    wearCount: 1,
    cost: 184.32,
    formality: "casual",
    img: "",
  },
  {
    id: "5",
    category: "shirt",
    brand: "Brand A",
    color: "red",
    size: "L",
    season: "winter",
    wearCount: 0,
    cost: 29.01,
    formality: "casual",
    img: "",
  },
  {
    id: "6",
    category: "skirt",
    brand: "Brand E",
    color: "yellow",
    size: "L",
    season: "summer",
    wearCount: 25,
    cost: 148.27,
    formality: "formal",
    img: "",
  },
  {
    id: "7",
    category: "dress",
    brand: "Brand C",
    color: "yellow",
    size: "S",
    season: "summer",
    wearCount: 8,
    cost: 147.37,
    formality: "formal",
    img: "",
  },
  {
    id: "8",
    category: "pants",
    brand: "Brand A",
    color: "black",
    size: "XXL",
    season: "autumn",
    wearCount: 17,
    cost: 27.19,
    formality: "formal",
    img: "",
  },
  {
    id: "9",
    category: "dress",
    brand: "Brand C",
    color: "red",
    size: "L",
    season: "summer",
    wearCount: 48,
    cost: 196.59,
    formality: "formal",
    img: "",
  },
  {
    id: "10",
    category: "jacket",
    brand: "Brand C",
    color: "blue",
    size: "S",
    season: "spring",
    wearCount: 45,
    cost: 130.25,
    formality: "formal",
    img: "",
  },
  {
    id: "11",
    category: "shirt",
    brand: "Brand E",
    color: "green",
    size: "M",
    season: "spring",
    wearCount: 7,
    cost: 167.14,
    formality: "formal",
    img: "",
  },
  {
    id: "12",
    category: "shirt",
    brand: "Brand C",
    color: "white",
    size: "S",
    season: "winter",
    wearCount: 39,
    cost: 92.74,
    formality: "sports",
    img: "",
  },
  {
    id: "13",
    category: "dress",
    brand: "Brand C",
    color: "black",
    size: "S",
    season: "winter",
    wearCount: 40,
    cost: 155.21,
    formality: "sports",
    img: "",
  },
  {
    id: "14",
    category: "dress",
    brand: "Brand B",
    color: "black",
    size: "L",
    season: "spring",
    wearCount: 0,
    cost: 106.51,
    formality: "sports",
    img: "",
  },
  {
    id: "15",
    category: "jacket",
    brand: "Brand B",
    color: "blue",
    size: "M",
    season: "winter",
    wearCount: 37,
    cost: 163.2,
    formality: "sports",
    img: "",
  },
  {
    id: "16",
    category: "pants",
    brand: "Brand C",
    color: "green",
    size: "XXL",
    season: "autumn",
    wearCount: 2,
    cost: 45.28,
    formality: "sports",
    img: "",
  },
  {
    id: "17",
    category: "pants",
    brand: "Brand D",
    color: "white",
    size: "S",
    season: "summer",
    wearCount: 4,
    cost: 150.29,
    formality: "sports",
    img: "",
  },
  {
    id: "18",
    category: "sweater",
    brand: "Brand A",
    color: "green",
    size: "XL",
    season: "summer",
    wearCount: 21,
    cost: 31.31,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "19",
    category: "shirt",
    brand: "Brand D",
    color: "green",
    size: "L",
    season: "summer",
    wearCount: 18,
    cost: 25.81,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "20",
    category: "sweater",
    brand: "Brand E",
    color: "green",
    size: "XXL",
    season: "autumn",
    wearCount: 14,
    cost: 38.03,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "21",
    category: "leggings",
    brand: "Brand A",
    color: "black",
    size: "M",
    season: "spring",
    wearCount: 5,
    cost: 25.50,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "22",
    category: "tights",
    brand: "Brand C",
    color: "red",
    size: "L",
    season: "winter",
    wearCount: 9,
    cost: 15.75,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "23",
    category: "socks",
    brand: "Brand B",
    color: "blue",
    size: "S",
    season: "summer",
    wearCount: 20,
    cost: 8.99,
    formality: "dressy casual",
    img: "",
  },
  {
    id: "24",
    category: "cardigan",
    brand: "Brand D",
    color: "grey",
    size: "XL",
    season: "autumn",
    wearCount: 12,
    cost: 45.30,
    formality: "gardening-tier",
    img: "",
  },
  {
    id: "25",
    category: "leggings",
    brand: "Brand F",
    color: "purple",
    size: "S",
    season: "winter",
    wearCount: 7,
    cost: 30.20,
    formality: "gardening-tier",
    img: "",
  },
  {
    id: "26",
    category: "leggings",
    brand: "Brand G",
    color: "pink",
    size: "L",
    season: "summer",
    wearCount: 3,
    cost: 22.10,
    formality: "gardening-tier",
    img: "",
  },
  {
    id: "27",
    category: "tights",
    brand: "Brand H",
    color: "yellow",
    size: "M",
    season: "spring",
    wearCount: 11,
    cost: 18.00,
    formality: "gardening-tier",
    img: "",
  },
  {
    id: "28",
    category: "tights",
    brand: "Brand I",
    color: "orange",
    size: "XL",
    season: "autumn",
    wearCount: 8,
    cost: 20.45,
    formality: "gardening-tier",
    img: "",
  },
  {
    id: "29",
    category: "socks",
    brand: "Brand J",
    color: "white",
    size: "XXL",
    season: "winter",
    wearCount: 15,
    cost: 5.99,
    formality: "workwear",
    img: "",
  },
  {
    id: "30",
    category: "socks",
    brand: "Brand K",
    color: "brown",
    size: "XS",
    season: "summer",
    wearCount: 10,
    cost: 7.50,
    formality: "workwear",
    img: "",
  },
  {
    id: "31",
    category: "cardigan",
    brand: "Brand L",
    color: "beige",
    size: "M",
    season: "spring",
    wearCount: 14,
    cost: 50.00,
    formality: "workwear",
    img: "",
  },
  {
    id: "32",
    category: "cardigan",
    brand: "Brand M",
    color: "blue",
    size: "XXL",
    season: "autumn",
    wearCount: 6,
    cost: 55.25,
    formality: "workwear",
    img: "",
  }




];

export default clothesArray;