const clothesArray = [
  {
    id: 1,
    category: "pants",
    brand: "Brand D",
    color: "blue",
    size: "XXL",
    season: "autumn",
    wearCount: 47,
    cost: 187.37,
  },
  {
    id: 2,
    category: "sweater",
    brand: "Brand B",
    color: "white",
    size: "S",
    season: "summer",
    wearCount: 32,
    cost: 30.25,
  },
  {
    id: 3,
    category: "pants",
    brand: "Brand C",
    color: "red",
    size: "XL",
    season: "spring",
    wearCount: 21,
    cost: 96.03,
  },
  {
    id: 4,
    category: "shirt",
    brand: "Brand B",
    color: "blue",
    size: "L",
    season: "spring",
    wearCount: 1,
    cost: 184.32,
  },
  {
    id: 5,
    category: "shirt",
    brand: "Brand A",
    color: "red",
    size: "L",
    season: "winter",
    wearCount: 0,
    cost: 29.01,
  },
  {
    id: 6,
    category: "skirt",
    brand: "Brand E",
    color: "yellow",
    size: "L",
    season: "summer",
    wearCount: 25,
    cost: 148.27,
  },
  {
    id: 7,
    category: "dress",
    brand: "Brand C",
    color: "yellow",
    size: "S",
    season: "summer",
    wearCount: 8,
    cost: 147.37,
  },
  {
    id: 8,
    category: "pants",
    brand: "Brand A",
    color: "black",
    size: "XXL",
    season: "autumn",
    wearCount: 17,
    cost: 27.19,
  },
  {
    id: 9,
    category: "dress",
    brand: "Brand C",
    color: "red",
    size: "L",
    season: "summer",
    wearCount: 48,
    cost: 196.59,
  },
  {
    id: 10,
    category: "jacket",
    brand: "Brand C",
    color: "blue",
    size: "S",
    season: "spring",
    wearCount: 45,
    cost: 130.25,
  },
  {
    id: 11,
    category: "shirt",
    brand: "Brand E",
    color: "green",
    size: "M",
    season: "spring",
    wearCount: 7,
    cost: 167.14,
  },
  {
    id: 12,
    category: "shirt",
    brand: "Brand C",
    color: "white",
    size: "S",
    season: "winter",
    wearCount: 39,
    cost: 92.74,
  },
  {
    id: 13,
    category: "dress",
    brand: "Brand C",
    color: "black",
    size: "S",
    season: "winter",
    wearCount: 40,
    cost: 155.21,
  },
  {
    id: 14,
    category: "dress",
    brand: "Brand B",
    color: "black",
    size: "L",
    season: "spring",
    wearCount: 0,
    cost: 106.51,
  },
  {
    id: 15,
    category: "jacket",
    brand: "Brand B",
    color: "blue",
    size: "M",
    season: "winter",
    wearCount: 37,
    cost: 163.2,
  },
  {
    id: 16,
    category: "pants",
    brand: "Brand C",
    color: "green",
    size: "XXL",
    season: "autumn",
    wearCount: 2,
    cost: 45.28,
  },
  {
    id: 17,
    category: "pants",
    brand: "Brand D",
    color: "white",
    size: "S",
    season: "summer",
    wearCount: 4,
    cost: 150.29,
  },
  {
    id: 18,
    category: "sweater",
    brand: "Brand A",
    color: "green",
    size: "XL",
    season: "summer",
    wearCount: 21,
    cost: 31.31,
  },
  {
    id: 19,
    category: "shirt",
    brand: "Brand D",
    color: "green",
    size: "L",
    season: "summer",
    wearCount: 18,
    cost: 25.81,
  },
  {
    id: 20,
    category: "sweater",
    brand: "Brand E",
    color: "green",
    size: "XXL",
    season: "autumn",
    wearCount: 14,
    cost: 38.03,
  },
];

export default clothesArray;